custom: ['https://pay.btc.horse#bitcoin:37iSWX4QdoayZXmuj13AExuhzSkfd7LuG6', 'https://pay.btc.horse#ethereum:0x10c993039CC831A1fe8230ddd82A0A13625Dd43E', 'https://pay.btc.horse#litecoin:M8bEQNPkZ66hoFGYJuMVntyjj9dmYo1wBf']
